/**
 * @author 
 *
 *   /\_/\  _     ___
 *  |>'v'<||"| -/\, ,`>
 *     -=Edelstein=-
 * 
 */
public class mainGUI extends javax.swing.JFrame {

    /**
     * Creates new form mainGUI
     */
    public mainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diameterLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        taxesLabel = new javax.swing.JLabel();
        grandTotalLabel = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        pizzaDiameter = new javax.swing.JTextField();
        subtotal = new javax.swing.JLabel();
        taxes = new javax.swing.JLabel();
        grandTotal = new javax.swing.JLabel();
        anchoviesLabel = new javax.swing.JLabel();
        olivesLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        flavorText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        diameterLabel.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        diameterLabel.setText("Diameter of Pizza (cm):");

        nameLabel.setFont(new java.awt.Font("FreeSerif", 1, 24)); // NOI18N
        nameLabel.setText("PUTRID PIZZA");

        subtotalLabel.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        subtotalLabel.setText("Subtotal:");

        taxesLabel.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        taxesLabel.setText("Taxes:");

        grandTotalLabel.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        grandTotalLabel.setText("Grand total:");

        calculate.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        calculate.setText("Calculate!");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        pizzaDiameter.setColumns(3);
        pizzaDiameter.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        pizzaDiameter.setText("0");
        pizzaDiameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaDiameterActionPerformed(evt);
            }
        });

        subtotal.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        subtotal.setText("0");

        taxes.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        taxes.setText("0");

        grandTotal.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        grandTotal.setText("0");

        anchoviesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anchovies.png"))); // NOI18N

        olivesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/olvies.png"))); // NOI18N

        flavorText.setFont(new java.awt.Font("FreeSerif", 1, 16)); // NOI18N
        flavorText.setText("         ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flavorText)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flavorText)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anchoviesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addComponent(olivesLabel))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subtotalLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(grandTotalLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(taxesLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subtotal)
                                    .addComponent(taxes)
                                    .addComponent(grandTotal))
                                .addGap(8, 8, 8))
                            .addComponent(diameterLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calculate, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pizzaDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(anchoviesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(nameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(olivesLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diameterLabel)
                            .addComponent(pizzaDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(calculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subtotalLabel)
                            .addComponent(subtotal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxesLabel)
                            .addComponent(taxes))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grandTotalLabel)
                            .addComponent(grandTotal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        //variables
        final double LABOR_COST       = 0.75;
        final double RENT_COST        = 0.99;
        final double TAX_AMOUNT       = 0.13;
        final double INGREDIENTS_COST = 0.50;
        
        final String DIAMETER_TEXT_ONE = "We are going to make you a cute little pizza!";
        final String DIAMETER_TEXT_TWO = "This will be delicious!";
        final String DIAMETER_TEXT_THREE = "Whoa, big pizza! You might need a truck to get this home!";
        final int DIAMETER_ONE = 1;
        final int DIAMETER_TWO = 15;
        final int DIAMETER_THREE = 40;
        
        double diameterValue;
        double subtotalValue;
        double taxValue;
        double grandTotalValue;
        String flavorTextValue = null;
        
        diameterValue = Double.parseDouble(pizzaDiameter.getText());
        
        
        //calculate
        subtotalValue = (diameterValue * INGREDIENTS_COST) + RENT_COST + LABOR_COST;
        taxValue = subtotalValue*TAX_AMOUNT;
        grandTotalValue = subtotalValue + taxValue;
        
            //rounding
        subtotalValue = round(subtotalValue);
        taxValue = round(taxValue);
        grandTotalValue = round(grandTotalValue);
        
        
        //elseif&&operator
        if(diameterValue>=DIAMETER_ONE && diameterValue<=DIAMETER_TWO){
            flavorTextValue = DIAMETER_TEXT_ONE;
        } else if(diameterValue>DIAMETER_TWO && diameterValue<DIAMETER_THREE){
            flavorTextValue = DIAMETER_TEXT_TWO;
        } else if(diameterValue>=DIAMETER_THREE){
            flavorTextValue = DIAMETER_TEXT_THREE;
        } else{
            System.out.println("Error: Invalid input.");
        }
        
        
        //output
        subtotal.setText(String.valueOf("$" + subtotalValue));
        taxes.setText(String.valueOf("$" + taxValue));
        grandTotal.setText(String.valueOf("$" + grandTotalValue));
        flavorText.setText(String.valueOf(flavorTextValue));
    }//GEN-LAST:event_calculateActionPerformed

    private static double round(double toRound) {
        //simple rounding
        toRound = toRound*100;
        toRound = Math.round(toRound);
        toRound = toRound / 100;
        return toRound;
    }
    
    private void pizzaDiameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaDiameterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pizzaDiameterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anchoviesLabel;
    private javax.swing.JButton calculate;
    private javax.swing.JLabel diameterLabel;
    private javax.swing.JLabel flavorText;
    private javax.swing.JLabel grandTotal;
    private javax.swing.JLabel grandTotalLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel olivesLabel;
    private javax.swing.JTextField pizzaDiameter;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel taxes;
    private javax.swing.JLabel taxesLabel;
    // End of variables declaration//GEN-END:variables
}
